config/routes.rb
Rails.application.routes.draw do
  resources :charlas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charla.rb
class Charla < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charlas_controller.rb
class CharlasController < ApplicationController
  before_action :set_charla, only: [:show, :edit, :update, :destroy]

  # GET /charlas
  # GET /charlas.json
  def index
    @charlas = Charla.all
  end

  # GET /charlas/1
  # GET /charlas/1.json
  def show
  end

  # GET /charlas/new
  def new
    @charla = Charla.new
  end

  # GET /charlas/1/edit
  def edit
  end

  # POST /charlas
  # POST /charlas.json
  def create
    @charla = Charla.new(charla_params)

    respond_to do |format|
      if @charla.save
        format.html { redirect_to @charla, notice: 'Charla was successfully created.' }
        format.json { render :show, status: :created, location: @charla }
      else
        format.html { render :new }
        format.json { render json: @charla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charlas/1
  # PATCH/PUT /charlas/1.json
  def update
    respond_to do |format|
      if @charla.update(charla_params)
        format.html { redirect_to @charla, notice: 'Charla was successfully updated.' }
        format.json { render :show, status: :ok, location: @charla }
      else
        format.html { render :edit }
        format.json { render json: @charla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charlas/1
  # DELETE /charlas/1.json
  def destroy
    @charla.destroy
    respond_to do |format|
      format.html { redirect_to charlas_url, notice: 'Charla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charla
      @charla = Charla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charla_params
      params.fetch(:charla, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charlas_helper.rb
module CharlasHelper
end

app/views/charlas/_form.html.erb
<%= form_with(model: charla, local: true) do |form| %>
  <% if charla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charla.errors.count, "error") %> prohibited this charla from being saved:</h2>

      <ul>
      <% charla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charlas/edit.html.erb
<h1>Editing Charla</h1>

<%= render 'form', charla: @charla %>

<%= link_to 'Show', @charla %> |
<%= link_to 'Back', charlas_path %>

app/views/charlas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Charlas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charlas.each do |charla| %>
      <tr>
        <td><%= link_to 'Show', charla %></td>
        <td><%= link_to 'Edit', edit_charla_path(charla) %></td>
        <td><%= link_to 'Destroy', charla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charla', new_charla_path %>

app/views/charlas/new.html.erb
<h1>New Charla</h1>

<%= render 'form', charla: @charla %>

<%= link_to 'Back', charlas_path %>

app/views/charlas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_charla_path(@charla) %> |
<%= link_to 'Back', charlas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>First</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>